name = "Fabritech"
author = "confusedalex"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b111ed602f69754d3b36c25fb1b582c7d59d62dfe10e4688aa43ec427ab64f2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
