name = "Fabritech"
author = "confusedalex"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb560b8ee7c3ad4587ec1b1474b57ece4c96db2980e96e16211c49b0d92938fb"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
