name = "Fabritech"
author = "confusedalex"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d3ed714665b67396015df975e4cb3a5d5901a92de23adeaef24f9bd0bd4b25b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
