name = "Fabritech"
author = "confusedalex"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f86ff2f8d0407686a70d7139f8edcbe9d5e638b788892abeae936375183f173"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
