name = "Fabritech"
author = "confusedalex"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d481651c58317a80beb375636ec21140cfe461f7e5fb5dd694384c6f384c727"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
