name = "Fabritech"
author = "confusedalex"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "671369d22dac31cfcd43314284328777f84753c2c10b5a8ef7f2c023eb4aab35"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
