name = "Fabritech"
author = "confusedalex"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca1f5048f6e7493aa03e0ee9cb57a6703680ee4bfdb7594bfcf3bb89c972bbd5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
