name = "Fabritech"
author = "confusedalex"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6456770577a87013196a6be36bb47f71ca0f5f8ef571488997337dc6b5c1f251"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
